/// Glosario del reporte: conceptos explicados y todas las medidas DAX con su fórmula.
/// Lo genera herramientas/generar_glosario.py en reportes/<slug>/glosario.csv.
table glosario
	lineageTag: fec85c5b-af12-5ca1-bcc6-7670d62dcdd8

	column N°
		dataType: int64
		formatString: 0
		lineageTag: 42b337ef-6fed-5927-b410-ed03365875af
		summarizeBy: none
		sourceColumn: n

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 9355cd3e-a156-5346-957d-66e0e943e044
		summarizeBy: none
		sourceColumn: tipo

		annotation SummarizationSetBy = Automatic

	column Sección
		dataType: string
		lineageTag: 49ae3b2a-fa68-5329-98d4-9edf7251c4f8
		summarizeBy: none
		sourceColumn: seccion

		annotation SummarizationSetBy = Automatic

	column Término
		dataType: string
		lineageTag: 9196c7fe-c543-5645-87c7-25e743bd07c2
		summarizeBy: none
		sourceColumn: termino

		annotation SummarizationSetBy = Automatic

	column Explicación
		dataType: string
		lineageTag: b78e9856-4762-5cb6-953d-b220afb726c0
		summarizeBy: none
		sourceColumn: explicacion

		annotation SummarizationSetBy = Automatic

	column 'Fórmula DAX'
		dataType: string
		lineageTag: 49344131-8e78-5a34-b2b8-712c745700ac
		summarizeBy: none
		sourceColumn: formula

		annotation SummarizationSetBy = Automatic

	partition glosario = m
		mode: import
		source =
				let
				    Origen = Csv.Document(Web.Contents("https://raw.githubusercontent.com/h-e-sanchez/centinela/main/reportes/estados-financieros/glosario.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				    Tipos = Table.TransformColumnTypes(Encabezados, {{"n", Int64.Type}, {"tipo", type text}, {"seccion", type text}, {"termino", type text}, {"explicacion", type text}, {"formula", type text}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

