/// Hecho único: una fila por año, mes, sucursal y cuenta, con presupuesto, forecast y real (montos.csv pivoteado por versión).
table desviacion
	lineageTag: e2f6bfe0-3cea-50d2-b4e0-f81032472671

	/// Suma del presupuesto en el contexto de filtro.
	measure 'Monto Presupuesto' = SUM(desviacion[monto_presupuesto])
		formatString: \$ #,##0
		displayFolder: 1. Montos
		lineageTag: 9c9e9c97-4352-50b3-a1d4-9d2501e21e2f

	/// Suma de la ejecución real.
	measure 'Monto Real' = SUM(desviacion[monto_real])
		formatString: \$ #,##0
		displayFolder: 1. Montos
		lineageTag: 658afa86-f421-5baa-9d61-faf62b248663

	/// Real menos presupuesto: positivo = sobregasto (o sobreventa en Ingresos).
	measure 'Desviación $' = [Monto Real] - [Monto Presupuesto]
		formatString: \$ #,##0;-\$ #,##0
		displayFolder: 2. Desviación
		lineageTag: e09ea996-f5f5-5886-a467-155a2f548baa

	/// Desviación relativa; DIVIDE evita el error por presupuesto cero.
	measure 'Desviación %' = DIVIDE([Desviación $], [Monto Presupuesto])
		formatString: 0.0%;-0.0%
		displayFolder: 2. Desviación
		lineageTag: 11304183-7ca0-5296-9e3f-f24688d5b81f

	/// Real sobre presupuesto.
	measure '% Cumplimiento' = DIVIDE([Monto Real], [Monto Presupuesto])
		formatString: 0.0%
		displayFolder: 2. Desviación
		lineageTag: de7fb996-13bb-5b00-9ac2-54f01f1e8b2b

	/// Líneas en Alerta o Crítica (umbral 5%).
	measure 'Líneas en Alerta' = CALCULATE(COUNTROWS(desviacion), desviacion[Estado Semáforo] <> "OK")
		formatString: 0
		displayFolder: 3. Semáforo
		lineageTag: de1e7387-6818-589a-82a3-b7e43e9affad

	/// Líneas sobre el umbral crítico (15%).
	measure 'Líneas en Crítica' = CALCULATE(COUNTROWS(desviacion), desviacion[Estado Semáforo] = "Crítica")
		formatString: 0
		displayFolder: 3. Semáforo
		lineageTag: fbcb72a4-eee3-59df-be3e-6dfd499162fc

	/// Proporción de líneas fuera de umbral.
	measure '% Líneas en Alerta' = DIVIDE([Líneas en Alerta], COUNTROWS(desviacion))
		formatString: 0.0%
		displayFolder: 3. Semáforo
		lineageTag: 57b3fbf4-e223-5c2f-9ede-8dfd7964dd82

	/// Ingresos − Costos − Gastos Operacionales, ejecución real.
	measure 'Resultado Operacional' =
			VAR ingresos = CALCULATE([Monto Real], desviacion[grupo_cuenta] = "Ingresos")
			VAR costos = CALCULATE([Monto Real], desviacion[grupo_cuenta] = "Costos")
			VAR gastos = CALCULATE([Monto Real], desviacion[grupo_cuenta] = "Gastos Operacionales")
			RETURN ingresos - costos - gastos
		formatString: \$ #,##0;-\$ #,##0
		displayFolder: 4. Estado de Resultados
		lineageTag: 60a754b1-2b8c-5212-9cf0-85f26df0589d

	/// El mismo subtotal sobre el presupuesto.
	measure 'Resultado Operacional Presupuesto' =
			VAR ingresos = CALCULATE([Monto Presupuesto], desviacion[grupo_cuenta] = "Ingresos")
			VAR costos = CALCULATE([Monto Presupuesto], desviacion[grupo_cuenta] = "Costos")
			VAR gastos = CALCULATE([Monto Presupuesto], desviacion[grupo_cuenta] = "Gastos Operacionales")
			RETURN ingresos - costos - gastos
		formatString: \$ #,##0;-\$ #,##0
		displayFolder: 4. Estado de Resultados
		lineageTag: 616355c6-0058-5255-a759-bd2507023dac

	/// Acumulado del año (time intelligence sobre la tabla Calendario).
	measure 'Real YTD' = TOTALYTD([Monto Real], Calendario[Date])
		formatString: \$ #,##0
		displayFolder: 5. Tiempo
		lineageTag: fcf4c0ac-c7b3-5abe-ba81-744e509cbe15

	/// Presupuesto acumulado del año.
	measure 'Presupuesto YTD' = TOTALYTD([Monto Presupuesto], Calendario[Date])
		formatString: \$ #,##0
		displayFolder: 5. Tiempo
		lineageTag: 06172c43-b306-518e-8d05-be082bd0da97

	/// Desviación acumulada del año.
	measure 'Desviación YTD %' = DIVIDE([Real YTD] - [Presupuesto YTD], [Presupuesto YTD])
		formatString: 0.0%;-0.0%
		displayFolder: 5. Tiempo
		lineageTag: 9350bea9-28af-5ef2-8a10-dcfa2c8e5368

	/// Ejecución real del mes previo.
	measure 'Real Mes Anterior' = CALCULATE([Monto Real], DATEADD(Calendario[Date], -1, MONTH))
		formatString: \$ #,##0
		displayFolder: 5. Tiempo
		lineageTag: 094ed395-f6bd-529e-92c9-8b8c03e7cf57

	/// Variación contra el mes anterior.
	measure 'Variación MoM %' = DIVIDE([Monto Real] - [Real Mes Anterior], [Real Mes Anterior])
		formatString: 0.0%;-0.0%
		displayFolder: 5. Tiempo
		lineageTag: 169215b6-1e01-58e0-b15a-fe947a4dba1b

	/// Texto para tarjetas: millones con un decimal, sin escalado automático del visual.
	measure 'KPI Presupuesto' = FORMAT([Monto Presupuesto] / 1000000, "$ #,0.0") & " MM"
		displayFolder: 0. Tarjetas ejecutivas
		lineageTag: cba20ecd-ec3f-5629-997f-e5c777e1fa36

	/// Texto para tarjetas.
	measure 'KPI Real' = FORMAT([Monto Real] / 1000000, "$ #,0.0") & " MM"
		displayFolder: 0. Tarjetas ejecutivas
		lineageTag: 4d483d8d-fce3-5c6c-ae30-5cd7aa89ee3b

	/// Texto para tarjetas.
	measure 'KPI Resultado Operacional' = FORMAT([Resultado Operacional] / 1000000, "$ #,0.0;-$ #,0.0") & " MM"
		displayFolder: 0. Tarjetas ejecutivas
		lineageTag: 07b5ee1d-5ed2-5e67-8ba7-27d66095866a

	/// Texto para tarjetas.
	measure 'KPI Resultado Operacional Presupuesto' = FORMAT([Resultado Operacional Presupuesto] / 1000000, "$ #,0.0;-$ #,0.0") & " MM"
		displayFolder: 0. Tarjetas ejecutivas
		lineageTag: c69f8bc4-1750-530a-aa5d-beab2d8ed2d3

	/// Texto para tarjetas.
	measure 'KPI Real YTD' = FORMAT([Real YTD] / 1000000, "$ #,0.0") & " MM"
		displayFolder: 0. Tarjetas ejecutivas
		lineageTag: 540e01ea-5d46-5062-b115-b71264506f9b

	/// Texto para tarjetas.
	measure 'KPI Presupuesto YTD' = FORMAT([Presupuesto YTD] / 1000000, "$ #,0.0") & " MM"
		displayFolder: 0. Tarjetas ejecutivas
		lineageTag: 08be9d64-523d-53a5-bf10-7ba7dc8410c0

	/// Color hex del semáforo para formato condicional (barras y matriz): 5% alerta, 15% crítica.
	measure 'Color Semáforo' =
			VAR d = [Desviación %]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(d), "#978F7E",
			        ABS(d) > 0.15, "#B23C26",
			        ABS(d) > 0.05, "#A67A2E",
			        "#4F7A52"
			    )
		displayFolder: 3. Semáforo
		lineageTag: dd12f78b-5f80-51f9-858c-3d68da444e50

	/// Desviación del Resultado Operacional contra su presupuesto (base: valor absoluto del presupuesto).
	measure 'Desviación RO %' = DIVIDE([Resultado Operacional] - [Resultado Operacional Presupuesto], ABS([Resultado Operacional Presupuesto]))
		formatString: 0.0%;-0.0%
		displayFolder: 4. Estado de Resultados
		lineageTag: 52a8f62c-97ce-5940-b745-2338dc5d79f5

	/// Color del escenario según el Resultado Operacional: verde sobre +2%, rojo bajo -2%, gris si es neutro.
	measure 'Color Resultado' =
			VAR d = [Desviación RO %]
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK(d), "#978F7E",
			        d >= 0.02, "#4F7A52",
			        d <= -0.02, "#B23C26",
			        "#978F7E"
			    )
		displayFolder: 4. Estado de Resultados
		lineageTag: b8a9d497-815d-5ad2-8c06-af52e119f96b

	/// Forecast 3+9: enero a marzo real, abril a diciembre re-proyectado con el run-rate del trimestre.
	measure 'Monto Forecast' = SUM(desviacion[monto_forecast])
		formatString: \$ #,##0
		displayFolder: 1. Montos
		lineageTag: 85d653cc-0534-57b3-8183-721b30945d97

	/// Costos y gastos operacionales ejecutados (todo lo que no es ingreso).
	measure 'Gasto Real' = CALCULATE([Monto Real], desviacion[grupo_cuenta] <> "Ingresos")
		formatString: \$ #,##0
		displayFolder: 1. Montos
		lineageTag: 782cbca8-6eb6-5991-9a15-31581241dbf9

	/// Efecto de la desviación en el Resultado Operacional: más ingreso suma, más gasto resta.
	measure 'Impacto en Resultado $' =
			VAR ingresos = CALCULATE([Desviación $], desviacion[grupo_cuenta] = "Ingresos")
			VAR egresos = CALCULATE([Desviación $], desviacion[grupo_cuenta] <> "Ingresos")
			RETURN ingresos - egresos
		formatString: \$ #,##0;-\$ #,##0
		displayFolder: 4. Estado de Resultados
		lineageTag: d2438304-a712-5a3b-afec-7ad4919dde59

	/// El mismo subtotal sobre el forecast.
	measure 'Resultado Operacional Forecast' =
			VAR ingresos = CALCULATE([Monto Forecast], desviacion[grupo_cuenta] = "Ingresos")
			VAR costos = CALCULATE([Monto Forecast], desviacion[grupo_cuenta] = "Costos")
			VAR gastos = CALCULATE([Monto Forecast], desviacion[grupo_cuenta] = "Gastos Operacionales")
			RETURN ingresos - costos - gastos
		formatString: \$ #,##0;-\$ #,##0
		displayFolder: 4. Estado de Resultados
		lineageTag: 339472ed-ac7a-5645-b2e3-57b1bbb4bee8

	/// Real menos forecast: lo que ni siquiera el forecast de marzo anticipó.
	measure 'Desviación vs Forecast $' = [Monto Real] - [Monto Forecast]
		formatString: \$ #,##0;-\$ #,##0
		displayFolder: 6. Forecast
		lineageTag: 016c2c4a-a17d-5d0c-835c-9f979c5a6d17

	/// Desviación relativa contra el forecast.
	measure 'Desviación vs Forecast %' = DIVIDE([Desviación vs Forecast $], [Monto Forecast])
		formatString: 0.0%;-0.0%
		displayFolder: 6. Forecast
		lineageTag: 35fe7a3b-d30c-5859-a772-6dd588a2ee14

	/// Cuánto corrigió el forecast al presupuesto original.
	measure 'Forecast vs Presupuesto %' = DIVIDE([Monto Forecast] - [Monto Presupuesto], [Monto Presupuesto])
		formatString: 0.0%;-0.0%
		displayFolder: 6. Forecast
		lineageTag: c575318e-ba0e-5ffe-ae8f-0e9cfe6ddb82

	/// Resultado Operacional real contra el del forecast.
	measure 'Desviación RO vs Forecast %' = DIVIDE([Resultado Operacional] - [Resultado Operacional Forecast], ABS([Resultado Operacional Forecast]))
		formatString: 0.0%;-0.0%
		displayFolder: 6. Forecast
		lineageTag: 4775ad1d-14cf-5e7a-9c0e-0b99b43af8fb

	/// Real del mismo periodo del año anterior.
	measure 'Real AA' = CALCULATE([Monto Real], SAMEPERIODLASTYEAR(Calendario[Date]))
		formatString: \$ #,##0
		displayFolder: 5. Tiempo
		lineageTag: 8c79a99b-b37c-5ba3-bc98-cc5ed4ca2c01

	/// Crecimiento contra el mismo periodo del año anterior.
	measure 'Var. interanual %' = DIVIDE([Monto Real] - [Real AA], [Real AA])
		formatString: 0.0%;-0.0%
		displayFolder: 5. Tiempo
		lineageTag: 267e3803-5b26-5515-a7e4-f578d091b622

	/// Suma de los últimos 12 meses hasta el periodo visible.
	measure 'Real Móvil 12m' = CALCULATE([Monto Real], DATESINPERIOD(Calendario[Date], MAX(Calendario[Date]), -12, MONTH))
		formatString: \$ #,##0
		displayFolder: 5. Tiempo
		lineageTag: 7412610f-ee8e-578f-b870-00f71a329a48

	/// Resultado Operacional del mismo periodo del año anterior.
	measure 'Resultado Operacional AA' = CALCULATE([Resultado Operacional], SAMEPERIODLASTYEAR(Calendario[Date]))
		formatString: \$ #,##0;-\$ #,##0
		displayFolder: 5. Tiempo
		lineageTag: dad32ab3-a31e-554e-9c06-38f0d5653941

	/// Variación interanual del Resultado Operacional (base: valor absoluto del año anterior).
	measure 'Var. RO interanual %' = DIVIDE([Resultado Operacional] - [Resultado Operacional AA], ABS([Resultado Operacional AA]))
		formatString: 0.0%;-0.0%
		displayFolder: 5. Tiempo
		lineageTag: dc2c25be-d97c-58b2-887d-355b870a9cfa

	/// Parte del gasto ejecutado que se mueve con la actividad.
	measure 'Gasto variable %' = DIVIDE(CALCULATE([Monto Real], desviacion[tipo_gasto] = "Variable"), [Gasto Real])
		formatString: 0.0%
		displayFolder: 7. Estructura de gasto
		lineageTag: 33e76e4c-7bb0-550b-9115-91d9fbd64760

	/// Texto para tarjetas.
	measure 'KPI Forecast' = FORMAT([Monto Forecast] / 1000000, "$ #,0.0") & " MM"
		displayFolder: 0. Tarjetas ejecutivas
		lineageTag: 25f83219-ae5c-57bf-9d73-2c3dd05fdf34

	/// Texto para tarjetas.
	measure 'KPI Real AA' = FORMAT([Real AA] / 1000000, "$ #,0.0") & " MM"
		displayFolder: 0. Tarjetas ejecutivas
		lineageTag: 0d2c80be-1806-5e37-9fff-b82b97dfa2e9

	/// Texto para tarjetas.
	measure 'KPI Impacto en Resultado' = FORMAT([Impacto en Resultado $] / 1000000, "$ #,0.0;-$ #,0.0") & " MM"
		displayFolder: 0. Tarjetas ejecutivas
		lineageTag: 3f7189de-f80d-50c1-943f-94477659080a

	column anio
		dataType: int64
		lineageTag: bcbaf994-619e-507f-872b-ab410dd7522b
		summarizeBy: none
		sourceColumn: anio

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: int64
		lineageTag: 6b44f863-7609-5402-8f2e-a5f08eeafcee
		summarizeBy: none
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column centro_costo
		dataType: string
		lineageTag: d63fc3dd-11ea-522d-827b-baaa435d1574
		summarizeBy: none
		sourceColumn: centro_costo

		annotation SummarizationSetBy = Automatic

	column componente
		dataType: string
		lineageTag: de55f77a-6ffa-5744-bceb-5b2f141e3ab4
		summarizeBy: none
		sourceColumn: componente

		annotation SummarizationSetBy = Automatic

	column grupo_cuenta
		dataType: string
		lineageTag: d1274a78-004c-53f3-8706-2586b6beece2
		summarizeBy: none
		sourceColumn: grupo_cuenta

		annotation SummarizationSetBy = Automatic

	column monto_presupuesto
		dataType: double
		isHidden
		formatString: \$ #,##0
		lineageTag: a318f41d-76b0-5b64-b96f-b63177f6ddb5
		summarizeBy: sum
		sourceColumn: monto_presupuesto

		annotation SummarizationSetBy = Automatic

	column monto_real
		dataType: double
		isHidden
		formatString: \$ #,##0
		lineageTag: b3698031-446e-5a3a-967d-38d9ae5b352a
		summarizeBy: sum
		sourceColumn: monto_real

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		formatString: Short Date
		lineageTag: ed4fd4f1-f6de-5ad8-bc9b-0dc34f3939d7
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	/// Mismo criterio que src/motor.py: estricto (>), alerta >5%, crítica >15%.
	column 'Estado Semáforo' =
			VAR ppto = desviacion[monto_presupuesto]
			VAR pct = DIVIDE(desviacion[monto_real] - ppto, ppto)
			RETURN
			    SWITCH(
			        TRUE(),
			        ppto = 0 && desviacion[monto_real] <> 0, "Crítica",
			        ABS(pct) > 0.15, "Crítica",
			        ABS(pct) > 0.05, "Alerta",
			        "OK"
			    )
		dataType: string
		lineageTag: 58dd9745-5424-5d24-bed7-4851f260d6a6
		summarizeBy: none

	column industria
		dataType: string
		lineageTag: 8a4a4a94-2093-5960-a0ab-16ed4e61bade
		summarizeBy: none
		sourceColumn: industria

		annotation SummarizationSetBy = Automatic

	column sucursal
		dataType: string
		lineageTag: 4996e023-b626-5bf9-8c9d-3bd1091f804e
		summarizeBy: none
		sourceColumn: sucursal

		annotation SummarizationSetBy = Automatic

	column cuenta
		dataType: string
		lineageTag: 1017e202-70fd-569e-a899-d492db3345f1
		summarizeBy: none
		sourceColumn: cuenta

		annotation SummarizationSetBy = Automatic

	column tipo_gasto
		dataType: string
		lineageTag: ff9a194d-1b11-5c1c-99a8-40986e0b5f8c
		summarizeBy: none
		sourceColumn: tipo_gasto

		annotation SummarizationSetBy = Automatic

	column monto_forecast
		dataType: double
		isHidden
		formatString: \$ #,##0
		lineageTag: 5d58dbd3-ea8c-5cc0-9433-8041a841a563
		summarizeBy: sum
		sourceColumn: monto_forecast

		annotation SummarizationSetBy = Automatic

	partition desviacion = m
		mode: import
		source =
				let
				    Tipos = {{"version", type text}, {"industria", type text}, {"anio", Int64.Type}, {"mes", Int64.Type}, {"sucursal", type text}, {"centro_costo", type text}, {"componente", type text}, {"cuenta", type text}, {"tipo_gasto", type text}, {"grupo_cuenta", type text}, {"monto", type number}},
				    Origen = Table.TransformColumnTypes(
				        Table.PromoteHeaders(
				            Csv.Document(Web.Contents(UrlDatos & "escenarios/montos.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				            [PromoteAllScalars = true]),
				        Tipos, "en-US"),
				    // Una columna por versión: cada línea queda con presupuesto, forecast y real (0 explícito si falta uno).
				    Pivoteado = Table.Pivot(Origen, {"Presupuesto", "Forecast", "Real"}, "version", "monto", List.Sum),
				    Renombrado = Table.RenameColumns(Pivoteado, {{"Presupuesto", "monto_presupuesto"}, {"Forecast", "monto_forecast"}, {"Real", "monto_real"}}),
				    Montos = {"monto_presupuesto", "monto_forecast", "monto_real"},
				    SinNulos = Table.ReplaceValue(Renombrado, null, 0, Replacer.ReplaceValue, Montos),
				    ConTipos = Table.TransformColumnTypes(SinNulos, List.Transform(Montos, each {_, type number})),
				    ConFecha = Table.AddColumn(ConTipos, "fecha", each #date([anio], [mes], 1), type date)
				in
				    ConFecha

	annotation PBI_ResultType = Table

