/// Horas ausentes por clínica, unidad, estamento y mes, y cómo se cubrieron.
table cobertura
	lineageTag: bb90d3f5-9498-5a91-b229-d69df9fc83c4

	/// Horas ausentes que la unidad necesita cubrir.
	measure 'Horas requeridas' = SUM(cobertura[horas_requeridas])
		formatString: #,##0
		displayFolder: 4. Cobertura
		lineageTag: 90342ac8-ecfb-59e5-99b2-069902295ff8

	/// Cubiertas con horas extra del propio equipo (recargo de 50%).
	measure 'Horas sobretiempo' = SUM(cobertura[horas_sobretiempo])
		formatString: #,##0
		displayFolder: 4. Cobertura
		lineageTag: bbd93540-39de-5cdd-a51d-8751085c5bd4

	/// Cubiertas con el pool interno de reemplazos.
	measure 'Horas pool' = SUM(cobertura[horas_pool])
		formatString: #,##0
		displayFolder: 4. Cobertura
		lineageTag: 7c61e4b0-a987-581d-9084-0f10a7af0c8b

	/// Cubiertas con personal de una empresa externa.
	measure 'Horas externo' = SUM(cobertura[horas_externo])
		formatString: #,##0
		displayFolder: 4. Cobertura
		lineageTag: 67c9a1f5-4f5c-552b-b36e-87d18f220a25

	/// Horas que quedaron sin reemplazo: carga para el resto del equipo.
	measure 'Horas no cubiertas' = SUM(cobertura[horas_no_cubiertas])
		formatString: #,##0
		displayFolder: 4. Cobertura
		lineageTag: ecc325b9-b504-5372-a467-7fcd8ce3a739

	/// Horas reemplazadas por cualquier modalidad.
	measure 'Horas cubiertas' = [Horas sobretiempo] + [Horas pool] + [Horas externo]
		formatString: #,##0
		displayFolder: 4. Cobertura
		lineageTag: d08c6483-78c3-58a7-a655-74c0a4030c8a

	/// Dependencia del sobretiempo: lo que el piloto busca bajar.
	measure '% cubierto con sobretiempo' = DIVIDE([Horas sobretiempo], [Horas requeridas])
		formatString: 0.0%
		displayFolder: 4. Cobertura
		lineageTag: a74c0770-a8c5-5d33-b489-bf62aae7657d

	/// Costo de todas las horas reemplazadas.
	measure 'Costo de cobertura' = SUMX(cobertura, cobertura[costo_sobretiempo] + cobertura[costo_pool] + cobertura[costo_externo])
		formatString: \$ #,##0
		displayFolder: 4. Cobertura
		lineageTag: b590f310-60e6-5d93-b375-7d0b270b23e7

	/// Costo promedio de una hora reemplazada.
	measure 'Costo por hora cubierta' = DIVIDE([Costo de cobertura], [Horas cubiertas])
		formatString: \$ #,##0
		displayFolder: 4. Cobertura
		lineageTag: 0adc7bf0-76b2-519d-8fb9-701a087748ba

	/// Enero a junio de 2025, antes de que Norte instale el pool.
	measure 'Costo/hora antes del piloto' = CALCULATE([Costo por hora cubierta], DATESBETWEEN(Calendario[Date], DATE(2025, 1, 1), DATE(2025, 6, 30)))
		formatString: \$ #,##0
		displayFolder: 4. Cobertura
		lineageTag: ac6e264f-048e-5af6-9a73-b343cc8eb2b8

	/// Octubre de 2025 en adelante, con el pool ya instalado (tres meses de marcha blanca).
	measure 'Costo/hora con piloto' = CALCULATE([Costo por hora cubierta], DATESBETWEEN(Calendario[Date], DATE(2025, 10, 1), DATE(2026, 12, 31)))
		formatString: \$ #,##0
		displayFolder: 4. Cobertura
		lineageTag: 10852df7-8909-5f14-b249-25bee6ed7618

	/// Norte frente a Centro y Sur, que no cambiaron de modelo: diferencia en diferencias.
	measure 'Cambio costo/hora %' = DIVIDE([Costo/hora con piloto], [Costo/hora antes del piloto]) - 1
		formatString: 0.0%;-0.0%
		displayFolder: 4. Cobertura
		lineageTag: c872ac1f-a5fc-52ce-bed3-97ea4c0d615b

	/// Lo que Norte habría pagado de más con su costo por hora anterior al piloto.
	measure 'Ahorro piloto Norte' =
			CALCULATE(
			    VAR horas = CALCULATE([Horas cubiertas], DATESBETWEEN(Calendario[Date], DATE(2025, 10, 1), DATE(2026, 12, 31)))
			    RETURN ([Costo/hora antes del piloto] - [Costo/hora con piloto]) * horas,
			    clinicas[clinica] = "Norte"
			)
		formatString: \$ #,##0
		displayFolder: 4. Cobertura
		lineageTag: 66f205a9-9661-555e-89e0-85156193617a

	column anio
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f2b11de8-3f70-5993-beb4-67614ab02a23
		summarizeBy: none
		sourceColumn: anio

		annotation SummarizationSetBy = Automatic

	column mes
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3601754f-bdd6-5c25-b43f-819a34c9bddb
		summarizeBy: none
		sourceColumn: mes

		annotation SummarizationSetBy = Automatic

	column horas_ausencia
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: b1694431-fb4b-5d0a-95c1-5e85b1e2e42e
		summarizeBy: sum
		sourceColumn: horas_ausencia

		annotation SummarizationSetBy = Automatic

	column horas_requeridas
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: 1ae365b5-9174-5462-85af-9139abbd48ca
		summarizeBy: sum
		sourceColumn: horas_requeridas

		annotation SummarizationSetBy = Automatic

	column horas_sobretiempo
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: f7d70769-5bc5-50a7-8f81-648b7e14472d
		summarizeBy: sum
		sourceColumn: horas_sobretiempo

		annotation SummarizationSetBy = Automatic

	column horas_pool
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: 7f36999d-f798-51ed-9624-4df6a661b094
		summarizeBy: sum
		sourceColumn: horas_pool

		annotation SummarizationSetBy = Automatic

	column horas_externo
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: 4d38263c-925a-5d2e-9884-d99eebdaebc4
		summarizeBy: sum
		sourceColumn: horas_externo

		annotation SummarizationSetBy = Automatic

	column horas_no_cubiertas
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: a359be01-f198-56d1-b088-323a961e1c1f
		summarizeBy: sum
		sourceColumn: horas_no_cubiertas

		annotation SummarizationSetBy = Automatic

	column costo_sobretiempo
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: 26178920-9f77-509a-b58d-6b48c57f1a1d
		summarizeBy: sum
		sourceColumn: costo_sobretiempo

		annotation SummarizationSetBy = Automatic

	column costo_pool
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: a0e56c74-a0c1-509f-af56-894a18af00aa
		summarizeBy: sum
		sourceColumn: costo_pool

		annotation SummarizationSetBy = Automatic

	column costo_externo
		dataType: double
		isHidden
		formatString: #,##0
		lineageTag: a6eade2d-42fd-5078-aeed-56580f8988b3
		summarizeBy: sum
		sourceColumn: costo_externo

		annotation SummarizationSetBy = Automatic

	column clinica
		dataType: string
		isHidden
		lineageTag: ab91f910-3f88-53a3-9d94-48f468785184
		summarizeBy: none
		sourceColumn: clinica

		annotation SummarizationSetBy = Automatic

	column unidad
		dataType: string
		isHidden
		lineageTag: ca6561df-2210-5f6f-a32e-ecd26e49b2f5
		summarizeBy: none
		sourceColumn: unidad

		annotation SummarizationSetBy = Automatic

	column estamento
		dataType: string
		isHidden
		lineageTag: 6ae19147-f947-532d-9cf1-f205332c2f67
		summarizeBy: none
		sourceColumn: estamento

		annotation SummarizationSetBy = Automatic

	column fecha
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 71bf01c0-aeba-5bc2-9260-92cf0d492d23
		summarizeBy: none
		sourceColumn: fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition cobertura = m
		mode: import
		source =
				let
				    Origen = LeerCsv("cobertura_mensual.csv", {{"anio", Int64.Type}, {"mes", Int64.Type}, {"clinica", type text}, {"unidad", type text}, {"estamento", type text}, {"horas_ausencia", type number}, {"horas_requeridas", type number}, {"horas_sobretiempo", type number}, {"horas_pool", type number}, {"horas_externo", type number}, {"horas_no_cubiertas", type number}, {"costo_sobretiempo", type number}, {"costo_pool", type number}, {"costo_externo", type number}}),
				    ConFecha = Table.AddColumn(Origen, "fecha", each #date([anio], [mes], 1), type date)
				in
				    ConFecha

	annotation PBI_ResultType = Table
