/// Glosario del reporte: conceptos explicados y todas las medidas DAX con su fórmula.
/// Lo genera herramientas/generar_glosario.py en reportes/<slug>/glosario.csv.
table glosario
	lineageTag: b9e92529-df50-5a0e-a2d5-cdd10ae474c0

	column N°
		dataType: int64
		formatString: 0
		lineageTag: 02cf8269-a6ce-5c6e-adbd-1cf589400a56
		summarizeBy: none
		sourceColumn: n

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: d1a2d047-5eba-5206-864f-42ace8bb1a15
		summarizeBy: none
		sourceColumn: tipo

		annotation SummarizationSetBy = Automatic

	column Sección
		dataType: string
		lineageTag: 5098625d-d7b2-5577-956f-0e06de024e72
		summarizeBy: none
		sourceColumn: seccion

		annotation SummarizationSetBy = Automatic

	column Término
		dataType: string
		lineageTag: 05982800-4c3d-5484-9c7c-f88cb35e9f9b
		summarizeBy: none
		sourceColumn: termino

		annotation SummarizationSetBy = Automatic

	column Explicación
		dataType: string
		lineageTag: 32d460ba-018d-5a62-945b-3062c89f3a05
		summarizeBy: none
		sourceColumn: explicacion

		annotation SummarizationSetBy = Automatic

	column 'Fórmula DAX'
		dataType: string
		lineageTag: e86156f4-abba-56d9-a65e-3e5472f8b886
		summarizeBy: none
		sourceColumn: formula

		annotation SummarizationSetBy = Automatic

	partition glosario = m
		mode: import
		source =
				let
				    Origen = Csv.Document(Web.Contents("https://raw.githubusercontent.com/h-e-sanchez/centinela/main/reportes/workforce/glosario.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Encabezados = Table.PromoteHeaders(Origen, [PromoteAllScalars = true]),
				    Tipos = Table.TransformColumnTypes(Encabezados, {{"n", Int64.Type}, {"tipo", type text}, {"seccion", type text}, {"termino", type text}, {"explicacion", type text}, {"formula", type text}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

